local helper = require("koffeelab.spec_helper")
local Connection = require("db/connection")

describe("db/connection", function()
  after_each(function()
    helper.teardown()
  end)

  it("opens and closes an in-memory connection", function()
    local conn = Connection.open(":memory:")
    assert.is_truthy(conn)
    assert.are.equal(2, tonumber(conn:rowexec("SELECT 1 + 1")))
    Connection.close()
  end)

  it("applies PRAGMA foreign_keys = ON", function()
    local conn = Connection.open(":memory:")
    assert.are.equal(1, tonumber(conn:rowexec("PRAGMA foreign_keys")))
    Connection.close()
  end)

  it("returns the cached handle for the same path", function()
    local a = Connection.open(":memory:")
    local b = Connection.open(":memory:")
    assert.are.equal(a, b)
    Connection.close()
  end)

  it("commits a successful transaction", function()
    local conn = Connection.open(":memory:")
    conn:exec("CREATE TABLE t (n INTEGER)")
    local ok = Connection.with_transaction(function(c)
      c:exec("INSERT INTO t (n) VALUES (1)")
      c:exec("INSERT INTO t (n) VALUES (2)")
      return true
    end)
    assert.is_true(ok)
    assert.are.equal(2, tonumber(conn:rowexec("SELECT COUNT(*) FROM t")))
    Connection.close()
  end)

  it("rolls back when the function raises", function()
    local conn = Connection.open(":memory:")
    conn:exec("CREATE TABLE t (n INTEGER)")
    local ok, err = Connection.with_transaction(function(c)
      c:exec("INSERT INTO t (n) VALUES (1)")
      error("boom")
    end)
    assert.is_nil(ok)
    assert.is_truthy(tostring(err):find("boom"))
    assert.are.equal(0, tonumber(conn:rowexec("SELECT COUNT(*) FROM t")))
    Connection.close()
  end)

  it("rolls back when the function returns nil, err", function()
    local conn = Connection.open(":memory:")
    conn:exec("CREATE TABLE t (n INTEGER)")
    local ok, err = Connection.with_transaction(function(c)
      c:exec("INSERT INTO t (n) VALUES (1)")
      return nil, "rejected"
    end)
    assert.is_nil(ok)
    assert.are.equal("rejected", err)
    assert.are.equal(0, tonumber(conn:rowexec("SELECT COUNT(*) FROM t")))
    Connection.close()
  end)
end)
