require("koffeelab.spec_helper")
local Format = require("util/format")

describe("util/format", function()
  describe("duration", function()
    it("renders the §1.15 reference values", function()
      assert.are.equal("15 min", Format.duration(900))
      assert.are.equal("2:45", Format.duration(165))
      assert.are.equal("2 h", Format.duration(7200))
      assert.are.equal("12 h", Format.duration(43200))
      assert.are.equal("24 h", Format.duration(86400))
    end)

    it("uses m:ss below an hour when not a whole minute", function()
      assert.are.equal("0:30", Format.duration(30))
      assert.are.equal("1:05", Format.duration(65))
    end)

    it("uses N min for whole sub-hour minutes", function()
      assert.are.equal("1 min", Format.duration(60))
      assert.are.equal("59 min", Format.duration(3540))
    end)

    it("uses h:mm:ss for hours with a remainder", function()
      assert.are.equal("1:01:00", Format.duration(3660))
      assert.are.equal("2:00:05", Format.duration(7205))
    end)

    it("handles zero and rejects nil / negative", function()
      assert.are.equal("0:00", Format.duration(0))
      assert.is_nil(Format.duration(nil))
      assert.is_nil(Format.duration(-1))
    end)
  end)

  describe("ratio", function()
    it("computes the brew ratio from water / dose", function()
      local label, kind = Format.ratio(300, 18)
      assert.are.equal("1 : 16.7", label)
      assert.are.equal("brew", kind)
    end)

    it("falls back to output / dose when water is NULL (espresso)", function()
      local label, kind = Format.ratio(nil, 18, 36)
      assert.are.equal("1 : 2.0", label)
      assert.are.equal("yield", kind)
    end)

    it("returns nil without a usable dose or numerator", function()
      assert.is_nil(Format.ratio(300, 0))
      assert.is_nil(Format.ratio(300, nil))
      assert.is_nil(Format.ratio(nil, 18, nil))
    end)
  end)

  describe("ratings", function()
    it("renders whole stars with no half", function()
      assert.are.equal("\u{2605}\u{2605}\u{2605}\u{2606}\u{2606}", Format.rating_stars(3))
      assert.are.equal("\u{2606}\u{2606}\u{2606}\u{2606}\u{2606}", Format.rating_stars(0))
      assert.is_nil(Format.rating_stars(nil))
    end)

    it("clamps out-of-range whole ratings", function()
      assert.are.equal("\u{2605}\u{2605}\u{2605}\u{2605}\u{2605}", Format.rating_stars(9))
    end)

    it("renders the session average to one decimal", function()
      assert.are.equal("4.7", Format.rating_decimal(4.6667))
      assert.is_nil(Format.rating_decimal(nil))
    end)

    it("renders an average as stars plus a half glyph", function()
      assert.are.equal("\u{2605}\u{2605}\u{2605}\u{00BD}\u{2606}", Format.rating_avg_stars(3.4))
      assert.are.equal("\u{2605}\u{2605}\u{2605}\u{2605}\u{2606}", Format.rating_avg_stars(3.8))
      assert.are.equal("\u{2605}\u{2605}\u{2605}\u{2606}\u{2606}", Format.rating_avg_stars(3.1))
      assert.are.equal("\u{2605}\u{2605}\u{2605}\u{2605}\u{2605}", Format.rating_avg_stars(5))
    end)
  end)

  describe("physical value helpers", function()
    it("labels roast levels and trims numbers", function()
      assert.are.equal("Medium", Format.roast_label(3))
      assert.is_nil(Format.roast_label(9))
      assert.are.equal("15 clicks", Format.grind(15, "clicks"))
      assert.are.equal("15.5 clicks", Format.grind(15.5, "clicks"))
      assert.are.equal("18 g", Format.grams(18))
      assert.are.equal("17.5 g", Format.grams(17.5))
      assert.are.equal("93\u{00B0}C", Format.temp_c(93))
      assert.are.equal("93.5\u{00B0}C", Format.temp_c(93.5))
    end)
  end)

  describe("parse_duration", function()
    it("parses clock forms", function()
      assert.are.equal(165, Format.parse_duration("2:45"))
      assert.are.equal(3723, Format.parse_duration("1:02:03"))
    end)

    it("parses bare and suffixed forms", function()
      assert.are.equal(90, Format.parse_duration("90"))
      assert.are.equal(900, Format.parse_duration("15 min"))
      assert.are.equal(900, Format.parse_duration("15m"))
      assert.are.equal(7200, Format.parse_duration("2 h"))
      assert.are.equal(5400, Format.parse_duration("1.5h"))
      assert.are.equal(45, Format.parse_duration("45s"))
    end)

    it("round-trips with duration for the reference values", function()
      for _, sec in ipairs { 165, 900, 7200, 43200, 86400 } do
        assert.are.equal(sec, Format.parse_duration(Format.duration(sec)))
      end
    end)

    it("rejects junk", function()
      assert.is_nil(Format.parse_duration(""))
      assert.is_nil(Format.parse_duration("abc"))
      assert.is_nil(Format.parse_duration("1:2:3:4"))
      assert.is_nil(Format.parse_duration(nil))
      assert.is_nil(Format.parse_duration("-5"))
    end)
  end)
end)
