require("koffeelab.spec_helper")
local V = require("util/validation")

describe("util/validation", function()
  it("checks non-empty strings", function()
    assert.is_true(V.is_nonempty_string("V60"))
    assert.is_false(V.is_nonempty_string("   "))
    assert.is_false(V.is_nonempty_string(""))
    assert.is_false(V.is_nonempty_string(nil))
  end)

  it("checks positive / non-negative numbers and their nil variants", function()
    assert.is_true(V.is_positive_number(0.1))
    assert.is_false(V.is_positive_number(0))
    assert.is_true(V.is_nonneg_number(0))
    assert.is_false(V.is_nonneg_number(-1))
    assert.is_true(V.is_positive_or_nil(nil))
    assert.is_false(V.is_positive_or_nil(0))
    assert.is_true(V.is_nonneg_or_nil(nil))
    assert.is_false(V.is_nonneg_or_nil(-2))
  end)

  it("checks 1..5 integer ratings", function()
    assert.is_true(V.is_rating(1))
    assert.is_true(V.is_rating(5))
    assert.is_false(V.is_rating(0))
    assert.is_false(V.is_rating(3.5))
    assert.is_true(V.is_rating_or_nil(nil))
    assert.is_false(V.is_rating_or_nil(6))
  end)

  it("checks roast levels, temperature modes and step types", function()
    assert.is_true(V.is_roast_level(3))
    assert.is_false(V.is_roast_level(0))
    assert.is_true(V.is_temperature_mode("hot"))
    assert.is_false(V.is_temperature_mode("warm"))
    assert.is_true(V.is_step_type("bloom"))
    assert.is_false(V.is_step_type("percolate"))
  end)

  it("checks grinder ranges (§3.14)", function()
    assert.is_true(V.grinder_range_ok(1, 30, 1))
    assert.is_false(V.grinder_range_ok(30, 1, 1))
    assert.is_false(V.grinder_range_ok(1, 30, 0))
  end)

  it("first_error returns the first failing message or nil", function()
    assert.is_nil(V.first_error { { true, "a" }, { true, "b" } })
    assert.are.equal("b", V.first_error { { true, "a" }, { false, "b" }, { false, "c" } })
  end)
end)
